services:
  mongo:
    image: mongo:7
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 20

  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports: ["6333:6333"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/readyz"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./api
    env_file:
      - .env.ci
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
      qdrant:
        condition: service_healthy
