name: CI - Build and Test CTI Dashboard

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build API service
        run: docker build ./api -t cti-dashboard-api:latest

      - name: Build Worker service
        run: docker build ./workers -t cti-dashboard-worker:latest

      - name: Validate docker-compose
        run: docker compose config
